### PR TITLE
LPS-XXXXX Vertical align .palette-item-inner in firefox via css class modifier

### PR DESCRIPTION
**Pull request by boton**

### CODE REVIEW

**Comment by boton** [comment]
lf:test:sf

**Comment by boton** [comment]
cf:test:sf

**Comment by boton** [comment]
ci:test:sf

**Comment by sandrodw3** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by sandrodw3** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/78936. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
