### PR TITLE
LPS-115055 Adapt jsp

### PR DESCRIPTION
**Pull request by sandrodw3**

### CODE REVIEW

**Comment by dgarciasarai** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by dgarciasarai** [comment]
ci:test:sf

**Comment by dgarciasarai** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:close

**Comment by Tim-Cao** [comment]
See https://github.com/liferay-echo/liferay-portal/pull/1037

**Pull request closed without merging**
