### PR TITLE
LPS-100039 Also adds test for Non existing Fragment Entry Links

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
ci:sf

**Comment by jkappler** [comment]
ci:test-relevant

**Comment by jkappler** [comment]
ci:stop

**Comment by sandrodw3** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by sandrodw3** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
