### PR TITLE
LPS-x Add fake theme for ease testing

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
ci:stop

**Comment by victorg1991** [comment]
ci:test:Relevant

**Comment by victorg1991** [comment]
ci:stop

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
