### PR TITLE
LPS-104981 Remove unused props

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
ci:test:relevant:a:no:que:no:hay

**Comment by sandrodw3** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by sandrodw3** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/81976. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
