### PR TITLE
LPS-106718

### PR DESCRIPTION
**Pull request by p2kmgcl**
cc @jbalsas

### CODE REVIEW

**Comment by p2kmgcl** [comment]
Hey @wincent @matuzalemsteles,
I added here a small type definition file to for some part of the application state. Could you have a look at it and tell me if you have any correction/suggestion? Thanks! :D

**Comment by wincent** [comment]
It looks ok to me, @p2kmgcl. The main thing is that it be complete enough to catch stuff like:

```javascript
state.misspelled  // Property 'misspelled' does not exist on type 'Type'
```

and it seems to do that.

**Comment by matuzalemsteles** [comment]
Sounds good for me! I hope we can increase this number of types soon 😁

**Comment by sandrodw3** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by sandrodw3** [comment]
Pull request submitted to https://github.com/ealonso/liferay-portal/pull/2755. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
