### PR TITLE
LPS-104264 Use the new ItemSelectorDialog

### PR DESCRIPTION
**Pull request by ambrinchaudhary**

### CODE REVIEW

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by sandrodw3** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by sandrodw3** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/80750. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by sandrodw3** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/80751. [See changes here.](https://github.com/sandrodw3/liferay-portal/compare/7c6f12ce3801~1...7c6f12ce3801) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
