### PR TITLE
LPS-117069 buildLang

### PR DESCRIPTION
**Pull request by sandrodw3**

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
@pavel-savinov

**Comment by Tim-Cao** [comment]
Please remove this commit https://github.com/sandrodw3/liferay-portal/pull/365/commits/2d222db569bad043300c050677111fc78379f7b5

**Comment by Tim-Cao** [comment]
See https://github.com/liferay-echo/liferay-portal/pull/1853

**Pull request closed without merging**
