### PR TITLE
LPS-117064, LPS-117066, LPS-117069 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-117064
https://issues.liferay.com/browse/LPS-117066
https://issues.liferay.com/browse/LPS-117069

This is only for master.

@sandrodw3 
@pavel-savinov

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
Hi @sandrodw3 and @pavel-savinov , Please have a look at integraion test failures.

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by pavel-savinov** [comment]
Just started reviewing :)

**Comment by Tim-Cao** [comment]
See https://github.com/sandrodw3/liferay-portal/pull/365

**Pull request closed without merging**
