### PR TITLE
LPS-107036 Don't use constant from the editor

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by sandrodw3** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by sandrodw3** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/83396. [See changes here.](https://github.com/sandrodw3/liferay-portal/compare/cf15dcbd4338~1...cf15dcbd4338) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by sandrodw3** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/83401. [See changes here.](https://github.com/sandrodw3/liferay-portal/compare/2c0d629a49f6~3...2c0d629a49f6) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
