### PR TITLE
LPS-103018 | Audience validation

### PR DESCRIPTION
**Pull request by andresfulla**

### CODE REVIEW

**Comment by dgarciasarai** [comment]
ci:test:sf

**Comment by dgarciasarai** [comment]
ci:test:relevant

**Comment by andresfulla** [comment]
ci:test:sf

**Comment by andresfulla** [comment]
ci:test:relevant

**Comment by sandrodw3** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by sandrodw3** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/79485. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
