### PR TITLE
LPS-114527 As a user, I would like to be able to move multiple pages through dragging in Pages Administration

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
Error
Please check your codes again.

**Comment by Tim-Cao** [comment]
ci:close

**Comment by sandrodw3** [comment]
> Error
> @sandrodw3
> Please check your codes again.
> Can not reproduce manually. Please run PortalSmoke#Smoke

🤔, ok! I'll take a look, thank you again @Tim-Cao!

**Pull request closed without merging**
