### PR TITLE
LPS-102900 | Experiment Navigation

### PR DESCRIPTION
**Pull request by andresfulla**
@dgarciasarai

### CODE REVIEW

**Comment by dgarciasarai** [comment]
ci:test:sf

**Comment by dgarciasarai** [comment]
ci:test:relevant

**Comment by andresfulla** [comment]
ci:test:relevant

**Comment by sandrodw3** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by sandrodw3** [comment]
Pull request submitted to https://github.com/ruben-pulido/liferay-portal/pull/138. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
