### PR TITLE
LPS-102073 Avoid image being rendered outside

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by sandrodw3** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by sandrodw3** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by sandrodw3** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/78724. [See changes here.](https://github.com/sandrodw3/liferay-portal/compare/37516802a7a6~1...37516802a7a6) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
